### PR TITLE
Improve game end view

### PR DESCRIPTION
**Pull request by jonchan51**
Landscape iphone 5:
image

Portrait iphone 5
image

Desktop
image

Think we need much more responsive font sizes to make the app look better on desktop in general

### CODE REVIEW

**Comment by Na-Nazhou** [comment]
And we also need to remove the 'Accuracy' from header when game ends

**Comment by Na-Nazhou** [comment]
Perhaps another improvement is to show an animation of increasing from 0% - xx% for the progress bar so the ending screen is not too static hahha

**Review by Na-Nazhou — APPROVED** [review]

**Comment by jonchan51** [comment]
Resolved both comments, can you check if the animation is good enough? I'm just using the inbuilt one provided by the library right now, which is just an animation that triggers on value change.

**Review by Na-Nazhou — APPROVED** [review]
LGTM

**Pull request merged**
